// Mocks generated by Mockito 5.4.6 from annotations
// in echo_protocol/test/unit/vault/vault_media_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i6;

import 'package:firebase_storage/firebase_storage.dart' as _i2;
import 'package:firebase_storage_platform_interface/firebase_storage_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseStorage_0 extends _i1.SmartFake
    implements _i2.FirebaseStorage {
  _FakeFirebaseStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_1 extends _i1.SmartFake implements _i2.Reference {
  _FakeReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMetadata_2 extends _i1.SmartFake implements _i3.FullMetadata {
  _FakeFullMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResult_3 extends _i1.SmartFake implements _i2.ListResult {
  _FakeListResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadTask_4 extends _i1.SmartFake implements _i2.UploadTask {
  _FakeUploadTask_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadTask_5 extends _i1.SmartFake implements _i2.DownloadTask {
  _FakeDownloadTask_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Reference].
///
/// See the documentation for Mockito's code generation for more information.
class MockReference extends _i1.Mock implements _i2.Reference {
  @override
  _i2.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_0(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeFirebaseStorage_0(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.FirebaseStorage);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  String get fullPath =>
      (super.noSuchMethod(
            Invocation.getter(#fullPath),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i4.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i2.Reference get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeReference_1(this, Invocation.getter(#root)),
            returnValueForMissingStub: _FakeReference_1(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i2.Reference);

  @override
  _i2.Reference child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeReference_1(
              this,
              Invocation.method(#child, [path]),
            ),
            returnValueForMissingStub: _FakeReference_1(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i2.Reference);

  @override
  _i5.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getDownloadURL() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadURL, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.FullMetadata> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i5.Future<_i3.FullMetadata>.value(
              _FakeFullMetadata_2(this, Invocation.method(#getMetadata, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.FullMetadata>.value(
              _FakeFullMetadata_2(this, Invocation.method(#getMetadata, [])),
            ),
          )
          as _i5.Future<_i3.FullMetadata>);

  @override
  _i5.Future<_i2.ListResult> list([_i3.ListOptions? options]) =>
      (super.noSuchMethod(
            Invocation.method(#list, [options]),
            returnValue: _i5.Future<_i2.ListResult>.value(
              _FakeListResult_3(this, Invocation.method(#list, [options])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ListResult>.value(
              _FakeListResult_3(this, Invocation.method(#list, [options])),
            ),
          )
          as _i5.Future<_i2.ListResult>);

  @override
  _i5.Future<_i2.ListResult> listAll() =>
      (super.noSuchMethod(
            Invocation.method(#listAll, []),
            returnValue: _i5.Future<_i2.ListResult>.value(
              _FakeListResult_3(this, Invocation.method(#listAll, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ListResult>.value(
              _FakeListResult_3(this, Invocation.method(#listAll, [])),
            ),
          )
          as _i5.Future<_i2.ListResult>);

  @override
  _i5.Future<_i6.Uint8List?> getData([int? maxSize = 10485760]) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [maxSize]),
            returnValue: _i5.Future<_i6.Uint8List?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Uint8List?>.value(),
          )
          as _i5.Future<_i6.Uint8List?>);

  @override
  _i2.UploadTask putData(
    _i6.Uint8List? data, [
    _i3.SettableMetadata? metadata,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#putData, [data, metadata]),
            returnValue: _FakeUploadTask_4(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_4(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
          )
          as _i2.UploadTask);

  @override
  _i2.UploadTask putBlob(dynamic blob, [_i3.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putBlob, [blob, metadata]),
            returnValue: _FakeUploadTask_4(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_4(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
          )
          as _i2.UploadTask);

  @override
  _i2.UploadTask putFile(_i7.File? file, [_i3.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putFile, [file, metadata]),
            returnValue: _FakeUploadTask_4(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_4(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
          )
          as _i2.UploadTask);

  @override
  _i2.UploadTask putString(
    String? data, {
    _i3.PutStringFormat? format = _i3.PutStringFormat.raw,
    _i3.SettableMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putString,
              [data],
              {#format: format, #metadata: metadata},
            ),
            returnValue: _FakeUploadTask_4(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
            returnValueForMissingStub: _FakeUploadTask_4(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
          )
          as _i2.UploadTask);

  @override
  _i5.Future<_i3.FullMetadata> updateMetadata(_i3.SettableMetadata? metadata) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetadata, [metadata]),
            returnValue: _i5.Future<_i3.FullMetadata>.value(
              _FakeFullMetadata_2(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.FullMetadata>.value(
              _FakeFullMetadata_2(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
          )
          as _i5.Future<_i3.FullMetadata>);

  @override
  _i2.DownloadTask writeToFile(_i7.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#writeToFile, [file]),
            returnValue: _FakeDownloadTask_5(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
            returnValueForMissingStub: _FakeDownloadTask_5(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
          )
          as _i2.DownloadTask);
}
