// Mocks generated by Mockito 5.4.6 from annotations
// in echo_protocol/test/unit/vault/vault_encryption_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:echo_protocol/services/secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i2.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> storePrivateKey(String? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#storePrivateKey, [privateKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPrivateKey() =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storePublicKey(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#storePublicKey, [publicKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPublicKey() =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storePartnerPublicKey(String? partnerPublicKey) =>
      (super.noSuchMethod(
            Invocation.method(#storePartnerPublicKey, [partnerPublicKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPartnerPublicKey() =>
      (super.noSuchMethod(
            Invocation.method(#getPartnerPublicKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storeUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#storeUserId, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storeSessionKey(String? sessionKey) =>
      (super.noSuchMethod(
            Invocation.method(#storeSessionKey, [sessionKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSessionKey() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  void clearSessionCache() => super.noSuchMethod(
    Invocation.method(#clearSessionCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasEncryptionKeys() =>
      (super.noSuchMethod(
            Invocation.method(#hasEncryptionKeys, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearEncryptionKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearEncryptionKeys, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasPartnerKey() =>
      (super.noSuchMethod(
            Invocation.method(#hasPartnerKey, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> storeTrustedFingerprint(String? fingerprint) =>
      (super.noSuchMethod(
            Invocation.method(#storeTrustedFingerprint, [fingerprint]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getTrustedFingerprint() =>
      (super.noSuchMethod(
            Invocation.method(#getTrustedFingerprint, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> isFingerprintAcknowledged() =>
      (super.noSuchMethod(
            Invocation.method(#isFingerprintAcknowledged, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearFingerprintAcknowledgment() =>
      (super.noSuchMethod(
            Invocation.method(#clearFingerprintAcknowledgment, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearTrustedFingerprint() =>
      (super.noSuchMethod(
            Invocation.method(#clearTrustedFingerprint, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeTwoFactorSecret(String? secret) =>
      (super.noSuchMethod(
            Invocation.method(#storeTwoFactorSecret, [secret]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getTwoFactorSecret() =>
      (super.noSuchMethod(
            Invocation.method(#getTwoFactorSecret, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storeBackupCodes(List<String>? codes) =>
      (super.noSuchMethod(
            Invocation.method(#storeBackupCodes, [codes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>?> getBackupCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupCodes, []),
            returnValue: _i3.Future<List<String>?>.value(),
          )
          as _i3.Future<List<String>?>);

  @override
  _i3.Future<void> clearTwoFactor() =>
      (super.noSuchMethod(
            Invocation.method(#clearTwoFactor, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeDeviceId(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#storeDeviceId, [deviceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storeArchivedKeyPair({
    required int? version,
    required String? publicKey,
    required String? privateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#storeArchivedKeyPair, [], {
              #version: version,
              #publicKey: publicKey,
              #privateKey: privateKey,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getArchivedPrivateKey(int? version) =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedPrivateKey, [version]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getArchivedPublicKey(int? version) =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedPublicKey, [version]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<List<int>> getArchivedKeyVersions() =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedKeyVersions, []),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<void> storeCurrentKeyVersion(int? version) =>
      (super.noSuchMethod(
            Invocation.method(#storeCurrentKeyVersion, [version]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int?> getCurrentKeyVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentKeyVersion, []),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<void> storePendingRecoveryPhrase(String? phrase) =>
      (super.noSuchMethod(
            Invocation.method(#storePendingRecoveryPhrase, [phrase]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPendingRecoveryPhrase() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRecoveryPhrase, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearPendingRecoveryPhrase() =>
      (super.noSuchMethod(
            Invocation.method(#clearPendingRecoveryPhrase, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeCacheKey(String? cacheKey) =>
      (super.noSuchMethod(
            Invocation.method(#storeCacheKey, [cacheKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getCacheKey() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteCacheKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCacheKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getLastSyncedChunkIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncedChunkIndex, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> storeLastSyncedChunkIndex(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#storeLastSyncedChunkIndex, [index]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLastSyncedChunkIndex() =>
      (super.noSuchMethod(
            Invocation.method(#deleteLastSyncedChunkIndex, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeVaultKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#storeVaultKey, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getVaultKey() =>
      (super.noSuchMethod(
            Invocation.method(#getVaultKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteVaultKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteVaultKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeDatabaseKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#storeDatabaseKey, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getDatabaseKey() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabaseKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteDatabaseKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDatabaseKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> storeSequenceCounters(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#storeSequenceCounters, [json]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSequenceCounters() =>
      (super.noSuchMethod(
            Invocation.method(#getSequenceCounters, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> get2FASessionVerified() =>
      (super.noSuchMethod(
            Invocation.method(#get2FASessionVerified, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> refresh2FASession() =>
      (super.noSuchMethod(
            Invocation.method(#refresh2FASession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Duration?> get2FASessionTimeRemaining() =>
      (super.noSuchMethod(
            Invocation.method(#get2FASessionTimeRemaining, []),
            returnValue: _i3.Future<Duration?>.value(),
          )
          as _i3.Future<Duration?>);
}
